/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditTrailRouteImport } from './routes/audit-trail'
import { Route as BlacklistRouteImport } from './routes/blacklist'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IdentraAiRouteImport } from './routes/identra-ai'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewVerificationRouteImport } from './routes/new-verification'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerificationCompleteRouteImport } from './routes/verification-complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTrailRoute = AuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const BlacklistRoute = BlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentraAiRoute = IdentraAiRouteImport.update({
  id: '/identra-ai',
  path: '/identra-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewVerificationRoute = NewVerificationRouteImport.update({
  id: '/new-verification',
  path: '/new-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationCompleteRoute = VerificationCompleteRouteImport.update({
  id: '/verification-complete',
  path: '/verification-complete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/blacklist': typeof BlacklistRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/identra-ai': typeof IdentraAiRoute
  '/login': typeof LoginRoute
  '/new-verification': typeof NewVerificationRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verification-complete': typeof VerificationCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/blacklist': typeof BlacklistRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/identra-ai': typeof IdentraAiRoute
  '/login': typeof LoginRoute
  '/new-verification': typeof NewVerificationRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verification-complete': typeof VerificationCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/blacklist': typeof BlacklistRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/identra-ai': typeof IdentraAiRoute
  '/login': typeof LoginRoute
  '/new-verification': typeof NewVerificationRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verification-complete': typeof VerificationCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-trail'
    | '/blacklist'
    | '/dashboard'
    | '/history'
    | '/identra-ai'
    | '/login'
    | '/new-verification'
    | '/screening'
    | '/settings'
    | '/signup'
    | '/verification-complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-trail'
    | '/blacklist'
    | '/dashboard'
    | '/history'
    | '/identra-ai'
    | '/login'
    | '/new-verification'
    | '/screening'
    | '/settings'
    | '/signup'
    | '/verification-complete'
  id:
    | '__root__'
    | '/'
    | '/audit-trail'
    | '/blacklist'
    | '/dashboard'
    | '/history'
    | '/identra-ai'
    | '/login'
    | '/new-verification'
    | '/screening'
    | '/settings'
    | '/signup'
    | '/verification-complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditTrailRoute: typeof AuditTrailRoute
  BlacklistRoute: typeof BlacklistRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  IdentraAiRoute: typeof IdentraAiRoute
  LoginRoute: typeof LoginRoute
  NewVerificationRoute: typeof NewVerificationRoute
  ScreeningRoute: typeof ScreeningRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerificationCompleteRoute: typeof VerificationCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blacklist': {
      id: '/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof BlacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identra-ai': {
      id: '/identra-ai'
      path: '/identra-ai'
      fullPath: '/identra-ai'
      preLoaderRoute: typeof IdentraAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-verification': {
      id: '/new-verification'
      path: '/new-verification'
      fullPath: '/new-verification'
      preLoaderRoute: typeof NewVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-complete': {
      id: '/verification-complete'
      path: '/verification-complete'
      fullPath: '/verification-complete'
      preLoaderRoute: typeof VerificationCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditTrailRoute: AuditTrailRoute,
  BlacklistRoute: BlacklistRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  IdentraAiRoute: IdentraAiRoute,
  LoginRoute: LoginRoute,
  NewVerificationRoute: NewVerificationRoute,
  ScreeningRoute: ScreeningRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerificationCompleteRoute: VerificationCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
